### ISSUE TITLE
Invalid validation state

### ISSUE THREAD

**Issue by stepanpelc** [sizek-cz/krv#2] opened 2023-10-02 02:32 UTC
### krv version

0.1.1

### Kubernetes distribution and version

kind 1.27.3

### Deployed validation

```shell
apiVersion: krv.sizek.cz/v1
kind: Validation
metadata:
  name: example-deployment-coredns
spec:
  name: "coredns"
  namespace: "kube-system"
  resource: "Deployment"
  validation:
    - jsonPath: "spec.name"
      value: "coredns"
```

### Steps to reproduce

Deploy validation

### Expected Behavior

Validation should be in OK state

### Actual Behavior

Validation is in NOK state

**Comment by romanfurst** [comment] 2024-04-01 15:09
the Validation has wrong jsonPath defined. Insead of `spec.name` should be `metadata.name`. Closing as not a bug

**Closed as completed by romanfurst** 2024-04-01 15:09 UTC
Labels: bug
